server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot?serverTimezone=UTC
    username: root
    password: lh1988
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations:
  - classpath*:com/shumu/**/mapper/xml/*Mapper.xml
  type-aliases-package: com/shumu/**/entity/;com/shumu/**/model/
shumu: 
  timeout: 
    account: 0
    credential: 0  
  locked: 
    time: 0
    count: 0
  uploadType: local
  path:
    #文件上传根目录 设置
    upload: /opt/upFiles
    #webapp文件路径
    webapp: /opt/webapp
  